trigger: none

jobs:
  - job: windows_build
    pool:
      vmImage: windows-latest
    displayName: Windows Build
    variables: 
      - name: sdk
        value: C:\\VulkanSDK
      - name: sdkSource
        value: https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
    steps:
      - task: Cache@2
        inputs:
          key: '"vulkansdk"'
          restoreKeys: vulkansdk
          path: ${{ variables.sdk }}
          cacheHitVar: SDK_CACHE_RESTORED
      - powershell: |
          Invoke-WebRequest -Uri "${{ variables.sdkSource }}" -OutFile VulkanSDK.exe
          $installer = Start-Process -FilePath VulkanSDK.exe -Wait -PassThru -ArgumentList @("/S");
          $installer.WaitForExit();
        displayName: Setup Vulkan
        condition: ne(variables.SDK_CACHE_RESTORED, 'true')
      - task: MSBuild@1
        env:
          VULKAN_SDK: ${{ variables.sdk }}
        inputs:
          environmentVariables: 
          solution: '**/*.sln'
          msbuildArchitecture: 'x64'
          platform: 'x64'
          configuration: 'Release'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\x64\Release\'
          ArtifactName: 'otterbuild'
          publishLocation: 'Container'
          StoreAsTar: true