trigger: none

jobs:
  - job: windows_build
    pool:
      vmImage: windows-latest
    displayName: Windows Build
    variables: 
      - name: sdk
        value: C:\\VulkanSDK
      - name: sdkSource
        value: https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
    steps:
      - powershell: |
          Invoke-WebRequest -Uri 'https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe' -OutFile 'vulkan-sdk.exe'
          .\vulkan-sdk.exe --root ${{ variables.sdk }} --accept-licenses --default-answer --confirm-command install
        displayName: 'Install Vulkan SDK'
      - task: VSBuild@1
        env:
          VULKAN_SDK: ${{ variables.sdk }}
        inputs:
          vsVersion: 'latest'
          solution: '**/*.sln'
          platform: 'x64'
          configuration: 'Release'
      - task: CopyFiles@2
        displayName: 'Stage Binaries'
        inputs:
          contents: 'x64\Release\?(*.exe|*.dll)'
          targetFolder: '$(Build.BinariesDirectory)'
      - task: ArchiveFiles@2
        displayName: 'Packaging Binaries'
        inputs:
          rootFolderOrFile: '$(Build.BinariesDirectory)'
          archiveType: 'zip'
          archiveFile: '$(Build.ArtifactStagingDirectory)/otterbuild-$(Build.BuildId).zip'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: '$(Build.ArtifactStagingDirectory)'
          artifactName: 'otterbuild'
          publishLocation: 'Container'