trigger: none

jobs:
  - job: windows_build
    pool:
      vmImage: windows-latest
    displayName: Windows Build
    variables: 
      - name: sdk
        value: C:\\VulkanSDK
      - name: sdkSource
        value: https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe
    steps:
      - task: Cache@2
        inputs:
          key: '"vulkansdk"'
          restoreKeys: vulkansdk
          path: ${{ variables.sdk }}
          cacheHitVar: SDK_CACHE_RESTORED
        displayName: Check For Cached VulkanSDK
      - powershell: |
          Invoke-WebRequest -Uri 'https://sdk.lunarg.com/sdk/download/latest/windows/vulkan-sdk.exe' -OutFile 'vulkan-sdk.exe'
          .\vulkan-sdk.exe --accept-licenses --default-answer --confirm-command install
        displayName: 'Install Vulkan SDK'
        condition: ne(variables.SDK_CACHE_RESTORED, 'true')
      - task: VSBuild@1
        env:
          VULKAN_SDK: ${{ variables.sdk }}
        inputs:
          vsVersion: 'latest'
          solution: '**/*.sln'
          platform: 'x64'
          configuration: 'Release'
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)\x64\Release\'
          ArtifactName: 'otterbuild'
          publishLocation: 'Container'
          StoreAsTar: true